name = "my-first-rust-cloudflare-worker"
workers_dev = true
compatibility_date = "2022-01-20"
main = "./build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.9"

# Commented out in order to avoid bug
# ref: https://github.com/cloudflare/workers-rs/issues/310
# [build]
# command = "cargo install -q worker-build && worker-build --release" # required
[build]
command = "cargo install -q worker-build --version ^0.0.8 && worker-build --release" # required

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
